spring:
  application:
    name: ai_agent
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma4:e2b
    mcp:
      client:
        streamable-http:
          connections:
            score-service:
              url: http://localhost:8090
              endpoint: /mcp
    chat:
      observations:
        include-prompt: true       # Sends prompts as trace tags
        include-completion: true   # Sends responses as trace tag

management:
  otlp:
    tracing:
      endpoint: http://localhost:4317 # Use a porta gRPC se estiver usando o starter OpenTelemetry
  tracing:
    enabled: true # Garante que o tracing está ativo
    sampling:
      probability: 1.0 # Força o envio de 100% das requisições (mude em produção)

logging:
  level:
    root: DEBUG